// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using clinivia_backend.Models;

#nullable disable

namespace clinivia_backend.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240604115619_INIT")]
    partial class INIT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("clinivia_backend.Models.Departement", b =>
                {
                    b.Property<int>("D_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("D_id"));

                    b.Property<DateTime>("D_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("D_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_head")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("D_no")
                        .HasColumnType("int");

                    b.Property<string>("D_status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("D_id");

                    b.ToTable("Departements");
                });
#pragma warning restore 612, 618
        }
    }
}
